### PR TITLE
Update French translation for gnome-3.16

### PR DESCRIPTION
**Pull request by neitsab**
After fiddling a bit with Poedit I managed to extract translatable strings from source, using `__` and `_e` as key words (see #180 for why I had to do this). From my tests it looks all good, I like the new commands in notifications!

PS: although I'm happy I learnt this way of doing I still hope you'll find time to address #180 :)
Cheers

### CODE REVIEW

**Comment by neitsab** [comment]
Updated the .po file to use the `intltool-update` procedure (thanks!)

**Comment by neitsab** [comment]
Updated PR with rebased changes from `gnome-3.16`, hope it's all good now!

**Comment by kamilprusko** [comment]
Looks great.

Thank you! :)

**Comment by neitsab** [comment]
Sweet, thanks! :)

**Pull request merged**
