### PR TITLE
Remove not existing Makefile.in

### PR DESCRIPTION
**Pull request by jubalh**

### CODE REVIEW

**Comment by kamilprusko** [comment]
It's not a bug... that Makefile is added by intltool during ./configure.

**Comment by jubalh** [comment]
```
[   88s] configure: creating ./config.status
[   89s] config.status: creating Makefile
[   89s] config.status: creating lib/Makefile
[   89s] config.status: creating src/Makefile
[   89s] config.status: creating data/Makefile
[   89s] config.status: creating data/icons/Makefile
[   89s] config.status: creating data/icons/16x16/Makefile
[   89s] config.status: creating data/icons/24x24/Makefile
[   89s] config.status: creating data/icons/32x32/Makefile
[   89s] config.status: creating data/icons/48x48/Makefile
[   89s] config.status: creating data/icons/256x256/Makefile
[   89s] config.status: creating data/icons/symbolic/Makefile
[   89s] config.status: creating data/sounds/Makefile
[   89s] config.status: error: cannot find input file: `po/Makefile.in.in'
```
Is what I get when building on OBS.
configure is being run

**Comment by kamilprusko** [comment]
Do you have gettext and intltool dependencies?

    BuildRequires: gettext
    BuildRequires: intltool

**Comment by jubalh** [comment]
Yes

**Pull request closed without merging**
