### PR TITLE
Add Indonesian translation

### PR DESCRIPTION
**Pull request by aliterm**
Hi, Codito
I've add a Indonesian translation.

### CODE REVIEW

**Comment by crayxt** [comment]
Hi,
1) Please delete the messages.mo file
2) Add your language code - ```id``` to LINGUAS file, keep it sorted alphabetically.
Regards,

**Comment by aliterm** [comment]
Hi cryxt,

I've delete the messages.mo file, and I've added id in LIGUAS file.

Thanks

**Comment by crayxt** [comment]
@aliterm Please sort the LINGUAS file alphabetically.

**Comment by aliterm** [comment]
Oke, I've sort the LINGUAS file alphabetically.

**Comment by crayxt** [comment]
@aliterm kudos, now let's wait for repository owner to respond ;)

**Comment by kamilprusko** [comment]
Looks ok :+1: Thank you

**Pull request merged**
